apiVersion: v1
kind: Secret
metadata:
  name: coworking-secret
type: Opaque
stringData:
  DB_PASSWORD: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: coworking-postgresql
type: Opaque
stringData:
  postgres-password: postgres
